#!/sbin/sh
# You can make your own debloater script
# Using the remove function
# Name it mindebloater.sh and put it where you put your zip
# Script will use your debloater instead of this one
# Please precede /system with $sysroot for wider compatibility

remove $sysroot/system/addon.d/70-gapps.sh
remove $sysroot/system/addon.d/71-faceunlock.sh
remove $sysroot/system/addon.d/71-gapps-faceunlock.sh
remove $sysroot/system/addon.d/74-googlecamera.sh
remove $sysroot/system/addon.d/74-googlegallery.sh
remove $sysroot/system/addon.d/75-googlegallery.sh
remove $sysroot/system/addon.d/78-chromebrowser.sh
remove $sysroot/system/app/AndroidForWork
remove $sysroot/system/app/AndroidForWork.apk
remove $sysroot/system/app/AndroidForWork.odex
remove $sysroot/system/app/BackupRestoreConfirmation
remove $sysroot/system/app/BackupRestoreConfirmation.apk
remove $sysroot/system/app/BackupRestoreConfirmation.odex
remove $sysroot/system/app/BasicDreams/BasicDreams.apk
remove $sysroot/system/app/Books
remove $sysroot/system/app/Books.apk
remove $sysroot/system/app/Books.odex
remove $sysroot/system/app/BooksPhone
remove $sysroot/system/app/BooksPhone.apk
remove $sysroot/system/app/BooksPhone.odex
remove $sysroot/system/app/BookmarkProvider/BookmarkProvider.apk
remove $sysroot/system/app/BookmarkProvider.odex
remove $sysroot/system/app/BrowserProviderProxy
remove $sysroot/system/app/BrowserProviderProxy.apk
remove $sysroot/system/app/BrowserProviderProxy.odex
remove $sysroot/system/app/CalculatorGoogle
remove $sysroot/system/app/CalculatorGoogle.apk
remove $sysroot/system/app/CalculatorGoogle.odex
remove $sysroot/system/app/CalculatorGooglePrebuilt
remove $sysroot/system/app/CalculatorGooglePrebuilt.apk
remove $sysroot/system/app/CalculatorGooglePrebuilt.odex
remove $sysroot/system/app/Calendar
remove $sysroot/system/app/Calendar.apk
remove $sysroot/system/app/Calendar.odex
remove $sysroot/system/app/CalendarGoogle
remove $sysroot/system/app/CalendarGoogle.apk
remove $sysroot/system/app/CalendarGoogle.odex
remove $sysroot/system/app/CalendarGooglePrebuilt
remove $sysroot/system/app/CalendarGooglePrebuilt.apk
remove $sysroot/system/app/CalendarGooglePrebuilt.odex
remove $sysroot/system/app/CalendarProvider
remove $sysroot/system/app/CalendarProvider.apk
remove $sysroot/system/app/CalendarProvider.odex
remove $sysroot/system/app/CarHomeGoogle
remove $sysroot/system/app/CarHomeGoogle.apk
remove $sysroot/system/app/CarHomeGoogle.odex
remove $sysroot/system/app/CellBroadcastReceiver
remove $sysroot/system/app/CellBroadcastReceiver.apk
remove $sysroot/system/app/CellBroadcastReceiver.odex
remove $sysroot/system/app/Chrome
remove $sysroot/system/app/Chrome.apk
remove $sysroot/system/app/Chrome.odex
remove $sysroot/system/app/ChromeBookmarksSyncAdapter
remove $sysroot/system/app/ChromeBookmarksSyncAdapter.apk
remove $sysroot/system/app/ChromeBookmarksSyncAdapter.odex
remove $sysroot/system/app/CloudPrint
remove $sysroot/system/app/CloudPrint.apk
remove $sysroot/system/app/CloudPrint.odex
remove $sysroot/system/app/CloudPrint2
remove $sysroot/system/app/CloudPrint2.apk
remove $sysroot/system/app/CloudPrint2.odex
remove $sysroot/system/app/ConfigUpdater
remove $sysroot/system/app/ConfigUpdater.apk
remove $sysroot/system/app/ConfigUpdater.odex
remove $sysroot/system/app/ConnMO
remove $sysroot/system/app/ConnMO.apk
remove $sysroot/system/app/ConnMO.odex
remove $sysroot/system/app/Currents
remove $sysroot/system/app/Currents.apk
remove $sysroot/system/app/Currents.odex
remove $sysroot/system/app/DeskClockGoogle
remove $sysroot/system/app/DeskClockGoogle.apk
remove $sysroot/system/app/DeskClockGoogle.odex
remove $sysroot/system/app/DMAgent
remove $sysroot/system/app/DMAgent.apk
remove $sysroot/system/app/DMAgent.odex
remove $sysroot/system/app/Drive
remove $sysroot/system/app/Drive.apk
remove $sysroot/system/app/Drive.odex
remove $sysroot/system/app/EditorsDocs
remove $sysroot/system/app/EditorsDocs.apk
remove $sysroot/system/app/EditorsDocs.odex
remove $sysroot/system/app/EditorsSheets
remove $sysroot/system/app/EditorsSheets.apk
remove $sysroot/system/app/EditorsSheets.odex
remove $sysroot/system/app/EditorsSlides
remove $sysroot/system/app/EditorsSlides.apk
remove $sysroot/system/app/EditorsSlides.odex
remove $sysroot/system/app/Email/Email.apk
remove $sysroot/system/app/ExactCalculator.apk
remove $sysroot/system/app/Exchange2/Exchange2.apk
remove $sysroot/system/app/ExchangeServices
remove $sysroot/system/app/ExchangeServices.apk
remove $sysroot/system/app/ExchangeServices.odex
remove $sysroot/system/app/FaceLock
remove $sysroot/system/app/FaceLock.apk
remove $sysroot/system/app/FaceLock.odex
remove $sysroot/system/app/Finsky
remove $sysroot/system/app/Finsky.apk
remove $sysroot/system/app/Finsky.odex
remove $sysroot/system/app/FitnessPrebuilt
remove $sysroot/system/app/FitnessPrebuilt.apk
remove $sysroot/system/app/FitnessPrebuilt.odex
remove $sysroot/system/app/FOTAKill
remove $sysroot/system/app/FOTAKill.apk
remove $sysroot/system/app/FOTAKill.odex
remove $sysroot/system/app/GalleryGoogle
remove $sysroot/system/app/GalleryGoogle.apk
remove $sysroot/system/app/GalleryGoogle.odex
remove $sysroot/system/app/GCS
remove $sysroot/system/app/GCS.apk
remove $sysroot/system/app/GCS.odex
remove $sysroot/system/app/GenieWidget
remove $sysroot/system/app/GenieWidget.apk
remove $sysroot/system/app/GenieWidget.odex
remove $sysroot/system/app/Gmail
remove $sysroot/system/app/Gmail.apk
remove $sysroot/system/app/Gmail.odex
remove $sysroot/system/app/Gmail2
remove $sysroot/system/app/Gmail2.apk
remove $sysroot/system/app/Gmail2.odex
remove $sysroot/system/app/GmsCore
remove $sysroot/system/app/GmsCore.apk
remove $sysroot/system/app/GmsCore.odex
remove $sysroot/system/app/GmsCoreSetupPrebuilt
remove $sysroot/system/app/GmsCoreSetupPrebuilt.apk
remove $sysroot/system/app/GmsCoreSetupPrebuilt.odex
remove $sysroot/system/app/GoogleBackupTransport
remove $sysroot/system/app/GoogleBackupTransport.apk
remove $sysroot/system/app/GoogleBackupTransport.odex
remove $sysroot/system/app/GoogleCalendar
remove $sysroot/system/app/GoogleCalendar.apk
remove $sysroot/system/app/GoogleCalendar.odex
remove $sysroot/system/app/GoogleCalendarSyncAdapter
remove $sysroot/system/app/GoogleCalendarSyncAdapter.apk
remove $sysroot/system/app/GoogleCalendarSyncAdapter.odex
remove $sysroot/system/app/GoogleCamera
remove $sysroot/system/app/GoogleCamera.apk
remove $sysroot/system/app/GoogleCamera.odex
remove $sysroot/system/app/GoogleCloudPrint
remove $sysroot/system/app/GoogleCloudPrint.apk
remove $sysroot/system/app/GoogleCloudPrint.odex
remove $sysroot/system/app/GoogleContacts
remove $sysroot/system/app/GoogleContacts.apk
remove $sysroot/system/app/GoogleContacts.odex
remove $sysroot/system/app/GoogleContactsSyncAdapter
remove $sysroot/system/app/GoogleContactsSyncAdapter.apk
remove $sysroot/system/app/GoogleContactsSyncAdapter.odex
remove $sysroot/system/app/GoogleDialer
remove $sysroot/system/app/GoogleDialer.apk
remove $sysroot/system/app/GoogleDialer.odex
remove $sysroot/system/app/GoogleEars
remove $sysroot/system/app/GoogleEars.apk
remove $sysroot/system/app/GoogleEars.odex
remove $sysroot/system/app/GoogleEarth
remove $sysroot/system/app/GoogleEarth.apk
remove $sysroot/system/app/GoogleEarth.odex
remove $sysroot/system/app/GoogleExtServices
remove $sysroot/system/app/GoogleExtServices.apk
remove $sysroot/system/app/GoogleExtServices.odex
remove $sysroot/system/app/GoogleExtShared
remove $sysroot/system/app/GoogleExtShared.apk
remove $sysroot/system/app/GoogleExtShared.odex
remove $sysroot/system/app/GoogleFeedback
remove $sysroot/system/app/GoogleFeedback.apk
remove $sysroot/system/app/GoogleFeedback.odex
remove $sysroot/system/app/GoogleHangouts
remove $sysroot/system/app/GoogleHangouts.apk
remove $sysroot/system/app/GoogleHangouts.odex
remove $sysroot/system/app/GoogleHindiIME
remove $sysroot/system/app/GoogleHindiIME.apk
remove $sysroot/system/app/GoogleHindiIME.odex
remove $sysroot/system/app/GoogleHome
remove $sysroot/system/app/GoogleHome.apk
remove $sysroot/system/app/GoogleHome.odex
remove $sysroot/system/app/GoogleJapaneseInput
remove $sysroot/system/app/GoogleJapaneseInput.apk
remove $sysroot/system/app/GoogleJapaneseInput.odex
remove $sysroot/system/app/GoogleKeep
remove $sysroot/system/app/GoogleKeep.apk
remove $sysroot/system/app/GoogleKeep.odex
remove $sysroot/system/app/GoogleLatinIme
remove $sysroot/system/app/GoogleLatinIme.apk
remove $sysroot/system/app/GoogleLatinIme.odex
remove $sysroot/system/app/GoogleLoginService
remove $sysroot/system/app/GoogleLoginService.apk
remove $sysroot/system/app/GoogleLoginService.odex
remove $sysroot/system/app/GoogleMusic
remove $sysroot/system/app/GoogleMusic.apk
remove $sysroot/system/app/GoogleMusic.odex
remove $sysroot/system/app/GoogleNow
remove $sysroot/system/app/GoogleNow.apk
remove $sysroot/system/app/GoogleNow.odex
remove $sysroot/system/app/GoogleNowVoiceSearch
remove $sysroot/system/app/GoogleNowVoiceSearch.apk
remove $sysroot/system/app/GoogleNowVoiceSearch.odex
remove $sysroot/system/app/GoogleOneTimeInitializer
remove $sysroot/system/app/GoogleOneTimeInitializer.apk
remove $sysroot/system/app/GoogleOneTimeInitializer.odex
remove $sysroot/system/app/GooglePackageInstaller
remove $sysroot/system/app/GooglePackageInstaller.apk
remove $sysroot/system/app/GooglePackageInstaller.odex
remove $sysroot/system/app/GooglePartnerSetup
remove $sysroot/system/app/GooglePartnerSetup.apk
remove $sysroot/system/app/GooglePartnerSetup.odex
remove $sysroot/system/app/GooglePinyinIME
remove $sysroot/system/app/GooglePinyinIME.apk
remove $sysroot/system/app/GooglePinyinIME.odex
remove $sysroot/system/app/GooglePlay
remove $sysroot/system/app/GooglePlay.apk
remove $sysroot/system/app/GooglePlay.odex
remove $sysroot/system/app/GooglePlus
remove $sysroot/system/app/GooglePlus.apk
remove $sysroot/system/app/GooglePlus.odex
remove $sysroot/system/app/GooglePrintRecommendationService
remove $sysroot/system/app/GooglePrintRecommendationService.apk
remove $sysroot/system/app/GooglePrintRecommendationService.odex
remove $sysroot/system/app/GoogleQuickSearchBox
remove $sysroot/system/app/GoogleQuickSearchBox.apk
remove $sysroot/system/app/GoogleQuickSearchBox.odex
remove $sysroot/system/app/GoogleServicesFramework
remove $sysroot/system/app/GoogleServicesFramework.apk
remove $sysroot/system/app/GoogleServicesFramework.odex
remove $sysroot/system/app/GoogleTTS
remove $sysroot/system/app/GoogleTTS.apk
remove $sysroot/system/app/GoogleTTS.odex
remove $sysroot/system/app/GoogleVrCore
remove $sysroot/system/app/GoogleVrCore.apk
remove $sysroot/system/app/GoogleVrCore.odex
remove $sysroot/system/app/GoogleZhuyinIME
remove $sysroot/system/app/GoogleZhuyinIME.apk
remove $sysroot/system/app/GoogleZhuyinIME.odex
remove $sysroot/system/app/Hangouts
remove $sysroot/system/app/Hangouts.apk
remove $sysroot/system/app/Hangouts.odex
remove $sysroot/system/app/HangoutsDialer
remove $sysroot/system/app/HangoutsDialer.apk
remove $sysroot/system/app/HangoutsDialer.odex
remove $sysroot/system/app/HoloSpiralWallpaper/HoloSpiralWallpaper.apk
remove $sysroot/system/app/HotwordEnrollment
remove $sysroot/system/app/HotwordEnrollment.apk
remove $sysroot/system/app/HotwordEnrollment.odex
remove $sysroot/system/app/iWnnIME
remove $sysroot/system/app/iWnnIME.apk
remove $sysroot/system/app/iWnnIME.odex
remove $sysroot/system/app/iWnnIME_Kbd_White
remove $sysroot/system/app/iWnnIME_Kbd_White.apk
remove $sysroot/system/app/iWnnIME_Kbd_White.odex
remove $sysroot/system/app/Jelly/Jelly.apk
remove $sysroot/system/app/Keep
remove $sysroot/system/app/Keep.apk
remove $sysroot/system/app/Keep.odex
remove $sysroot/system/app/KoreanIME
remove $sysroot/system/app/KoreanIME.apk
remove $sysroot/system/app/KoreanIME.odex
remove $sysroot/system/app/LatinIME
remove $sysroot/system/app/LatinIME.apk
remove $sysroot/system/app/LatinIME.odex
remove $sysroot/system/app/LatinImeDictionaryPack
remove $sysroot/system/app/LatinImeDictionaryPack.apk
remove $sysroot/system/app/LatinImeDictionaryPack.odex
remove $sysroot/system/app/LatinImeGoogle
remove $sysroot/system/app/LatinImeGoogle.apk
remove $sysroot/system/app/LatinImeGoogle.odex
remove $sysroot/system/app/LatinIMEGooglePrebuilt
remove $sysroot/system/app/LatinIMEGooglePrebuilt.apk
remove $sysroot/system/app/LatinIMEGooglePrebuilt.odex
remove $sysroot/system/app/LatinImeTutorial
remove $sysroot/system/app/LatinImeTutorial.apk
remove $sysroot/system/app/LatinImeTutorial.odex
remove $sysroot/system/app/Magazines
remove $sysroot/system/app/Magazines.apk
remove $sysroot/system/app/Magazines.odex
remove $sysroot/system/app/Maps
remove $sysroot/system/app/Maps.apk
remove $sysroot/system/app/Maps.odex
remove $sysroot/system/app/MarketUpdater
remove $sysroot/system/app/MarketUpdater.apk
remove $sysroot/system/app/MarketUpdater.odex
remove $sysroot/system/app/MediaUploader
remove $sysroot/system/app/MediaUploader.apk
remove $sysroot/system/app/MediaUploader.odex
remove $sysroot/system/app/Music2
remove $sysroot/system/app/Music2.apk
remove $sysroot/system/app/Music2.odex
remove $sysroot/system/app/NetworkLocation
remove $sysroot/system/app/NetworkLocation.apk
remove $sysroot/system/app/NetworkLocation.odex
remove $sysroot/system/app/Newsstand
remove $sysroot/system/app/Newsstand.apk
remove $sysroot/system/app/Newsstand.odex
remove $sysroot/system/app/NexusLauncherIcons
remove $sysroot/system/app/NexusLauncherIcons.apk
remove $sysroot/system/app/NexusLauncherIcons.odex
remove $sysroot/system/app/NexusLauncherPrebuilt
remove $sysroot/system/app/NexusLauncherPrebuilt.apk
remove $sysroot/system/app/NexusLauncherPrebuilt.odex
remove $sysroot/system/app/NoiseField/NoiseField.apk
remove $sysroot/system/app/OccamQuickOffice
remove $sysroot/system/app/OccamQuickOffice.apk
remove $sysroot/system/app/OccamQuickOffice.odex
remove $sysroot/system/app/OneTimeInitializer
remove $sysroot/system/app/OneTimeInitializer.apk
remove $sysroot/system/app/OneTimeInitializer.odex
remove $sysroot/system/app/PartnerBookmarksProvider
remove $sysroot/system/app/PartnerBookmarksProvider.apk
remove $sysroot/system/app/PartnerBookmarksProvider.odex
remove $sysroot/system/app/PhaseBeam/PhaseBeam.apk
remove $sysroot/system/app/Phonesky
remove $sysroot/system/app/Phonesky.apk
remove $sysroot/system/app/Phonesky.odex
remove $sysroot/system/app/Photos
remove $sysroot/system/app/Photos.apk
remove $sysroot/system/app/Photos.odex
remove $sysroot/system/app/PhotoPhase/PhotoPhase.apk
remove $sysroot/system/app/PlayAutoInstallConfig
remove $sysroot/system/app/PlayAutoInstallConfig.apk
remove $sysroot/system/app/PlayAutoInstallConfig.odex
remove $sysroot/system/app/PlayGames
remove $sysroot/system/app/PlayGames.apk
remove $sysroot/system/app/PlayGames.odex
remove $sysroot/system/app/PlayStore
remove $sysroot/system/app/PlayStore.apk
remove $sysroot/system/app/PlayStore.odex
remove $sysroot/system/app/PlusOne
remove $sysroot/system/app/PlusOne.apk
remove $sysroot/system/app/PlusOne.odex
remove $sysroot/system/app/PrebuiltBugle
remove $sysroot/system/app/PrebuiltBugle.apk
remove $sysroot/system/app/PrebuiltBugle.odex
remove $sysroot/system/app/PrebuiltDeskClockGoogle
remove $sysroot/system/app/PrebuiltDeskClockGoogle.apk
remove $sysroot/system/app/PrebuiltDeskClockGoogle.odex
remove $sysroot/system/app/PrebuiltEmailGoogle
remove $sysroot/system/app/PrebuiltEmailGoogle.apk
remove $sysroot/system/app/PrebuiltEmailGoogle.odex
remove $sysroot/system/app/PrebuiltExchange3Google
remove $sysroot/system/app/PrebuiltExchange3Google.apk
remove $sysroot/system/app/PrebuiltExchange3Google.odex
remove $sysroot/system/app/PrebuiltGmail
remove $sysroot/system/app/PrebuiltGmail.apk
remove $sysroot/system/app/PrebuiltGmail.odex
remove $sysroot/system/app/PrebuiltGmsCore
remove $sysroot/system/app/PrebuiltGmsCore.apk
remove $sysroot/system/app/PrebuiltGmsCore.odex
remove $sysroot/system/app/PrebuiltKeep
remove $sysroot/system/app/PrebuiltKeep.apk
remove $sysroot/system/app/PrebuiltKeep.odex
remove $sysroot/system/app/PrebuiltNewsWeather
remove $sysroot/system/app/PrebuiltNewsWeather.apk
remove $sysroot/system/app/PrebuiltNewsWeather.odex
remove $sysroot/system/app/PrintSpooler
remove $sysroot/system/app/PrintSpooler.apk
remove $sysroot/system/app/PrintSpooler.odex
remove $sysroot/system/app/QuickOffice
remove $sysroot/system/app/QuickOffice.apk
remove $sysroot/system/app/QuickOffice.odex
remove $sysroot/system/app/QuickSearchBox
remove $sysroot/system/app/QuickSearchBox.apk
remove $sysroot/system/app/QuickSearchBox.odex
remove $sysroot/system/app/ResurrectionStats/ResurrectionStats.apk
remove $sysroot/system/app/SetupWizard
remove $sysroot/system/app/SetupWizard.apk
remove $sysroot/system/app/SetupWizard.odex
remove $sysroot/system/app/StorageManagerGoogle
remove $sysroot/system/app/StorageManagerGoogle.apk
remove $sysroot/system/app/StorageManagerGoogle.odex
remove $sysroot/system/app/Street
remove $sysroot/system/app/Street.apk
remove $sysroot/system/app/Street.odex
remove $sysroot/system/app/TagGoogle
remove $sysroot/system/app/TagGoogle.apk
remove $sysroot/system/app/TagGoogle.odex
remove $sysroot/system/app/Talk
remove $sysroot/system/app/Talk.apk
remove $sysroot/system/app/Talk.odex
remove $sysroot/system/app/talkback
remove $sysroot/system/app/talkback.apk
remove $sysroot/system/app/talkback.odex
remove $sysroot/system/app/TranslatePrebuilt
remove $sysroot/system/app/TranslatePrebuilt.apk
remove $sysroot/system/app/TranslatePrebuilt.odex
remove $sysroot/system/app/Tycho
remove $sysroot/system/app/Tycho.apk
remove $sysroot/system/app/Tycho.odex
remove $sysroot/system/app/Velvet
remove $sysroot/system/app/Velvet.apk
remove $sysroot/system/app/Velvet.odex
remove $sysroot/system/app/Vending
remove $sysroot/system/app/Vending.apk
remove $sysroot/system/app/Vending.odex
remove $sysroot/system/app/Videos
remove $sysroot/system/app/Videos.apk
remove $sysroot/system/app/Videos.odex
remove $sysroot/system/app/VoiceSearch
remove $sysroot/system/app/VoiceSearch.apk
remove $sysroot/system/app/VoiceSearch.odex
remove $sysroot/system/app/VoiceSearchStub
remove $sysroot/system/app/VoiceSearchStub.apk
remove $sysroot/system/app/VoiceSearchStub.odex
remove $sysroot/system/app/Wallet
remove $sysroot/system/app/Wallet.apk
remove $sysroot/system/app/Wallet.odex
remove $sysroot/system/app/WallpaperPickerGooglePrebuilt
remove $sysroot/system/app/WallpaperPickerGooglePrebuilt.apk
remove $sysroot/system/app/WallpaperPickerGooglePrebuilt.odex
remove $sysroot/system/app/WebViewGoogle
remove $sysroot/system/app/WebViewGoogle.apk
remove $sysroot/system/app/WebViewGoogle.odex
remove $sysroot/system/app/WebViewStub
remove $sysroot/system/app/WebViewStub.apk
remove $sysroot/system/app/WebViewStub.odex
remove $sysroot/system/app/YouTube
remove $sysroot/system/app/YouTube.apk
remove $sysroot/system/app/YouTube.odex
remove $sysroot/system/bin/wmdsi
remove $sysroot/system/etc/default-permissions/default-permissions.xml
remove $sysroot/system/etc/g.prop
remove $sysroot/system/etc/permissions/com.google.android.camera.experimental2015.xml
remove $sysroot/system/etc/permissions/com.google.android.camera.experimental2016.xml
remove $sysroot/system/etc/permissions/com.google.android.camera2.xml
remove $sysroot/system/etc/permissions/com.google.android.dialer.support.xml
remove $sysroot/system/etc/permissions/com.google.android.maps.xml
remove $sysroot/system/etc/permissions/com.google.android.media.effects.xml
remove $sysroot/system/etc/permissions/com.google.android.pano.v1.xml
remove $sysroot/system/etc/permissions/com.google.widevine.software.drm.xml
remove $sysroot/system/etc/permissions/features.xml
remove $sysroot/system/etc/preferred-apps/google.xml
remove $sysroot/system/etc/sysconfig/google.xml
remove $sysroot/system/etc/sysconfig/google_build.xml
remove $sysroot/system/etc/updatecmds/google_generic_update.txt
remove $sysroot/system/framework/com.google.android.camera.experimental2015.jar
remove $sysroot/system/framework/com.google.android.camera.experimental2016.jar
remove $sysroot/system/framework/com.google.android.camera2.jar
remove $sysroot/system/framework/com.google.android.dialer.support.jar
remove $sysroot/system/framework/com.google.android.maps.jar
remove $sysroot/system/framework/com.google.android.media.effects.jar
remove $sysroot/system/framework/com.google.android.pano.v1.jar
remove $sysroot/system/framework/com.google.widevine.software.drm.jar
remove $sysroot/system/lib/lib_dic_*
remove $sysroot/system/lib/libAppDataSearch.so
remove $sysroot/system/lib/libbitmap_parcel.so
remove $sysroot/system/lib/libchrome*
remove $sysroot/system/lib/libchromeview.so
remove $sysroot/system/lib/libconscrypt_gmscore_jni.so
remove $sysroot/system/lib/libcrashreporter.so
remove $sysroot/system/lib/libdocscanner*
remove $sysroot/system/lib/libdocsimageutils.so
remove $sysroot/system/lib/libearthandroid.so
remove $sysroot/system/lib/libearthmobile.so
remove $sysroot/system/lib/libEnjemailuri.so
remove $sysroot/system/lib/libennjcon.so
remove $sysroot/system/lib/libennjubase*
remove $sysroot/system/lib/libennjyomi.so
remove $sysroot/system/lib/libfacelock_jni.so
remove $sysroot/system/lib/libfacenet.so
remove $sysroot/system/lib/libfacetracker.so
remove $sysroot/system/lib/libfilterframework_jni.so
remove $sysroot/system/lib/libfilterpack_facedetect.so
remove $sysroot/system/lib/libflint_engine_jni_api.so
remove $sysroot/system/lib/libfoxit.so
remove $sysroot/system/lib/libframesequence.so
remove $sysroot/system/lib/libfrsdk.so
remove $sysroot/system/lib/libgames_rtmp_jni.so
remove $sysroot/system/lib/libgcam.so
remove $sysroot/system/lib/libgcam_swig_jni.so
remove $sysroot/system/lib/libgcastv2*
remove $sysroot/system/lib/libgcomm_jni.so
remove $sysroot/system/lib/libgmm-jni.so
remove $sysroot/system/lib/libgms-ocrclient.so
remove $sysroot/system/lib/libgmscore.so
remove $sysroot/system/lib/libgoggles_clientvision.so
remove $sysroot/system/lib/libgoogle_*
remove $sysroot/system/lib/libgtalk_jni.so
remove $sysroot/system/lib/libgtalk_stabilize.so
remove $sysroot/system/lib/libiwnn.so
remove $sysroot/system/lib/libjgcastservice.so
remove $sysroot/system/lib/libjni_eglfence.so
remove $sysroot/system/lib/libjni_filtershow_filters.so
remove $sysroot/system/lib/libjni_googlepinyinime_*
remove $sysroot/system/lib/libjni_koreanime.so
remove $sysroot/system/lib/libjni_latinime.so
remove $sysroot/system/lib/libjni_latinimegoogle.so
remove $sysroot/system/lib/libjni_t13n_shared_engine.so
remove $sysroot/system/lib/libjni_tinyplanet.so
remove $sysroot/system/lib/libjni_unbundled_latinimegoogle.so
remove $sysroot/system/lib/liblightcycle.so
remove $sysroot/system/lib/liblinearalloc.so
remove $sysroot/system/lib/libm2ts_player.so
remove $sysroot/system/lib/libmicro_hotword_jni.so
remove $sysroot/system/lib/libmoviemaker-jni.so
remove $sysroot/system/lib/libnativehelper_compat.so
remove $sysroot/system/lib/libnativehelper_compat_libc++.so
remove $sysroot/system/lib/libndk1.so
remove $sysroot/system/lib/libnetjni.so
remove $sysroot/system/lib/libnjaddress.so
remove $sysroot/system/lib/libnjcon.so
remove $sysroot/system/lib/libnjemoji.so
remove $sysroot/system/lib/libnjexyomi.so
remove $sysroot/system/lib/libnjfzk.so
remove $sysroot/system/lib/libnjkaomoji.so
remove $sysroot/system/lib/libnjname.so
remove $sysroot/system/lib/libnjtan.so
remove $sysroot/system/lib/libnjubase*
remove $sysroot/system/lib/libnjubaseidx1.so
remove $sysroot/system/lib/libnjubaseidx2.so
remove $sysroot/system/lib/libocrclient.so
remove $sysroot/system/lib/libpatts_engine_*
remove $sysroot/system/lib/libphotoeditor_native.so
remove $sysroot/system/lib/libpicowrapper.so
remove $sysroot/system/lib/libplus_jni_v8.so
remove $sysroot/system/lib/librectifier*
remove $sysroot/system/lib/librefocus.so
remove $sysroot/system/lib/librs.antblur.so
remove $sysroot/system/lib/librs.antblur_*
remove $sysroot/system/lib/librs.drama.so
remove $sysroot/system/lib/librs.film_base.so
remove $sysroot/system/lib/librs.fixedframe.so
remove $sysroot/system/lib/librs.grey.so
remove $sysroot/system/lib/librs.image_wrapper.so
remove $sysroot/system/lib/librs.layered_filter_f32.so
remove $sysroot/system/lib/librs.retrolux.so
remove $sysroot/system/lib/librsjni.so
remove $sysroot/system/lib/libRSSupport.so
remove $sysroot/system/lib/libspeexwrapper.so
remove $sysroot/system/lib/libspeexwrapper_ub*
remove $sysroot/system/lib/libsslwrapper_jni.so
remove $sysroot/system/lib/libstlport_shared.so
remove $sysroot/system/lib/libvcdecoder_jni.so
remove $sysroot/system/lib/libvideochat_jni.so
remove $sysroot/system/lib/libvideochat_stabilize.so
remove $sysroot/system/lib/libvoicesearch.so
remove $sysroot/system/lib/libvorbisencoder.so
remove $sysroot/system/lib/libwebp_android.so
remove $sysroot/system/lib/libwebrtc_audio_coding.so
remove $sysroot/system/lib/libWhisper.so
remove $sysroot/system/lib/libWVphoneAPI.so
remove $sysroot/system/lib/modules/modules.dep.bb
remove $sysroot/system/lib64/lib_dic_*
remove $sysroot/system/lib64/libAppDataSearch.so
remove $sysroot/system/lib64/libbitmap_parcel.so
remove $sysroot/system/lib64/libchrome*
remove $sysroot/system/lib64/libchromeview.so
remove $sysroot/system/lib64/libconscrypt_gmscore_jni.so
remove $sysroot/system/lib64/libcrashreporter.so
remove $sysroot/system/lib64/libdocscanner*
remove $sysroot/system/lib64/libdocsimageutils.so
remove $sysroot/system/lib64/libearthandroid.so
remove $sysroot/system/lib64/libearthmobile.so
remove $sysroot/system/lib64/libEnjemailuri.so
remove $sysroot/system/lib64/libennjcon.so
remove $sysroot/system/lib64/libennjubase*
remove $sysroot/system/lib64/libennjyomi.so
remove $sysroot/system/lib64/libfacelock_jni.so
remove $sysroot/system/lib64/libfacenet.so
remove $sysroot/system/lib64/libfacetracker.so
remove $sysroot/system/lib64/libfilterframework_jni.so
remove $sysroot/system/lib64/libfilterpack_facedetect.so
remove $sysroot/system/lib64/libflint_engine_jni_api.so
remove $sysroot/system/lib64/libfoxit.so
remove $sysroot/system/lib64/libframesequence.so
remove $sysroot/system/lib64/libfrsdk.so
remove $sysroot/system/lib64/libgames_rtmp_jni.so
remove $sysroot/system/lib64/libgcam.so
remove $sysroot/system/lib64/libgcam_swig_jni.so
remove $sysroot/system/lib64/libgcastv2*
remove $sysroot/system/lib64/libgcomm_jni.so
remove $sysroot/system/lib64/libgmm-jni.so
remove $sysroot/system/lib64/libgms-ocrclient.so
remove $sysroot/system/lib64/libgmscore.so
remove $sysroot/system/lib64/libgoggles_clientvision.so
remove $sysroot/system/lib64/libgoogle_*
remove $sysroot/system/lib64/libgtalk_jni.so
remove $sysroot/system/lib64/libgtalk_stabilize.so
remove $sysroot/system/lib64/libiwnn.so
remove $sysroot/system/lib64/libjgcastservice.so
remove $sysroot/system/lib64/libjni_eglfence.so
remove $sysroot/system/lib64/libjni_filtershow_filters.so
remove $sysroot/system/lib64/libjni_googlepinyinime_*
remove $sysroot/system/lib64/libjni_koreanime.so
remove $sysroot/system/lib64/libjni_latinime.so
remove $sysroot/system/lib64/libjni_latinimegoogle.so
remove $sysroot/system/lib64/libjni_t13n_shared_engine.so
remove $sysroot/system/lib64/libjni_tinyplanet.so
remove $sysroot/system/lib64/libjni_unbundled_latinimegoogle.so
remove $sysroot/system/lib64/liblightcycle.so
remove $sysroot/system/lib64/liblinearalloc.so
remove $sysroot/system/lib64/libm2ts_player.so
remove $sysroot/system/lib64/libmicro_hotword_jni.so
remove $sysroot/system/lib64/libmoviemaker-jni.so
remove $sysroot/system/lib64/libnativehelper_compat.so
remove $sysroot/system/lib64/libnativehelper_compat_libc++.so
remove $sysroot/system/lib64/libndk1.so
remove $sysroot/system/lib64/libnetjni.so
remove $sysroot/system/lib64/libnjaddress.so
remove $sysroot/system/lib64/libnjcon.so
remove $sysroot/system/lib64/libnjemoji.so
remove $sysroot/system/lib64/libnjexyomi.so
remove $sysroot/system/lib64/libnjfzk.so
remove $sysroot/system/lib64/libnjkaomoji.so
remove $sysroot/system/lib64/libnjname.so
remove $sysroot/system/lib64/libnjtan.so
remove $sysroot/system/lib64/libnjubase*
remove $sysroot/system/lib64/libnjubaseidx1.so
remove $sysroot/system/lib64/libnjubaseidx2.so
remove $sysroot/system/lib64/libocrclient.so
remove $sysroot/system/lib64/libpatts_engine_*
remove $sysroot/system/lib64/libphotoeditor_native.so
remove $sysroot/system/lib64/libpicowrapper.so
remove $sysroot/system/lib64/libplus_jni_v8.so
remove $sysroot/system/lib64/librectifier*
remove $sysroot/system/lib64/librefocus.so
remove $sysroot/system/lib64/librs.antblur.so
remove $sysroot/system/lib64/librs.antblur_*
remove $sysroot/system/lib64/librs.drama.so
remove $sysroot/system/lib64/librs.film_base.so
remove $sysroot/system/lib64/librs.fixedframe.so
remove $sysroot/system/lib64/librs.grey.so
remove $sysroot/system/lib64/librs.image_wrapper.so
remove $sysroot/system/lib64/librs.layered_filter_f32.so
remove $sysroot/system/lib64/librs.retrolux.so
remove $sysroot/system/lib64/librsjni.so
remove $sysroot/system/lib64/libRSSupport.so
remove $sysroot/system/lib64/libspeexwrapper.so
remove $sysroot/system/lib64/libspeexwrapper_ub*
remove $sysroot/system/lib64/libsslwrapper_jni.so
remove $sysroot/system/lib64/libstlport_shared.so
remove $sysroot/system/lib64/libvcdecoder_jni.so
remove $sysroot/system/lib64/libvideochat_jni.so
remove $sysroot/system/lib64/libvideochat_stabilize.so
remove $sysroot/system/lib64/libvoicesearch.so
remove $sysroot/system/lib64/libvorbisencoder.so
remove $sysroot/system/lib64/libwebp_android.so
remove $sysroot/system/lib64/libwebrtc_audio_coding.so
remove $sysroot/system/lib64/libWhisper.so
remove $sysroot/system/lib64/libWVphoneAPI.so
remove $sysroot/system/lib64/modules/modules.dep.bb
remove $sysroot/system/priv-app/AndroidForWork
remove $sysroot/system/priv-app/AndroidForWork.apk
remove $sysroot/system/priv-app/AndroidForWork.odex
remove $sysroot/system/priv-app/BackupRestoreConfirmation
remove $sysroot/system/priv-app/BackupRestoreConfirmation.apk
remove $sysroot/system/priv-app/BackupRestoreConfirmation.odex
remove $sysroot/system/priv-app/Books
remove $sysroot/system/priv-app/Books.apk
remove $sysroot/system/priv-app/Books.odex
remove $sysroot/system/priv-app/BooksPhone
remove $sysroot/system/priv-app/BooksPhone.apk
remove $sysroot/system/priv-app/BooksPhone.odex
remove $sysroot/system/priv-app/BrowserProviderProxy
remove $sysroot/system/priv-app/BrowserProviderProxy.apk
remove $sysroot/system/priv-app/BrowserProviderProxy.odex
remove $sysroot/system/priv-app/CalculatorGoogle
remove $sysroot/system/priv-app/CalculatorGoogle.apk
remove $sysroot/system/priv-app/CalculatorGoogle.odex
remove $sysroot/system/priv-app/CalculatorGooglePrebuilt
remove $sysroot/system/priv-app/CalculatorGooglePrebuilt.apk
remove $sysroot/system/priv-app/CalculatorGooglePrebuilt.odex
remove $sysroot/system/priv-app/Calendar
remove $sysroot/system/priv-app/Calendar.apk
remove $sysroot/system/priv-app/Calendar.odex
remove $sysroot/system/priv-app/CalendarGoogle
remove $sysroot/system/priv-app/CalendarGoogle.apk
remove $sysroot/system/priv-app/CalendarGoogle.odex
remove $sysroot/system/priv-app/CalendarGooglePrebuilt
remove $sysroot/system/priv-app/CalendarGooglePrebuilt.apk
remove $sysroot/system/priv-app/CalendarGooglePrebuilt.odex
remove $sysroot/system/priv-app/CalendarProvider
remove $sysroot/system/priv-app/CalendarProvider.apk
remove $sysroot/system/priv-app/CalendarProvider.odex
remove $sysroot/system/priv-app/CarHomeGoogle
remove $sysroot/system/priv-app/CarHomeGoogle.apk
remove $sysroot/system/priv-app/CarHomeGoogle.odex
remove $sysroot/system/priv-app/CellBroadcastReceiver
remove $sysroot/system/priv-app/CellBroadcastReceiver.apk
remove $sysroot/system/priv-app/CellBroadcastReceiver.odex
remove $sysroot/system/priv-app/Chrome
remove $sysroot/system/priv-app/Chrome.apk
remove $sysroot/system/priv-app/Chrome.odex
remove $sysroot/system/priv-app/ChromeBookmarksSyncAdapter
remove $sysroot/system/priv-app/ChromeBookmarksSyncAdapter.apk
remove $sysroot/system/priv-app/ChromeBookmarksSyncAdapter.odex
remove $sysroot/system/priv-app/CloudPrint
remove $sysroot/system/priv-app/CloudPrint.apk
remove $sysroot/system/priv-app/CloudPrint.odex
remove $sysroot/system/priv-app/CloudPrint2
remove $sysroot/system/priv-app/CloudPrint2.apk
remove $sysroot/system/priv-app/CloudPrint2.odex
remove $sysroot/system/priv-app/ConfigUpdater
remove $sysroot/system/priv-app/ConfigUpdater.apk
remove $sysroot/system/priv-app/ConfigUpdater.odex
remove $sysroot/system/priv-app/ConnMO
remove $sysroot/system/priv-app/ConnMO.apk
remove $sysroot/system/priv-app/ConnMO.odex
remove $sysroot/system/priv-app/Currents
remove $sysroot/system/priv-app/Currents.apk
remove $sysroot/system/priv-app/Currents.odex
remove $sysroot/system/priv-app/DeskClockGoogle
remove $sysroot/system/priv-app/DeskClockGoogle.apk
remove $sysroot/system/priv-app/DeskClockGoogle.odex
remove $sysroot/system/priv-app/DMAgent
remove $sysroot/system/priv-app/DMAgent.apk
remove $sysroot/system/priv-app/DMAgent.odex
remove $sysroot/system/priv-app/Drive
remove $sysroot/system/priv-app/Drive.apk
remove $sysroot/system/priv-app/Drive.odex
remove $sysroot/system/priv-app/EditorsDocs
remove $sysroot/system/priv-app/EditorsDocs.apk
remove $sysroot/system/priv-app/EditorsDocs.odex
remove $sysroot/system/priv-app/EditorsSheets
remove $sysroot/system/priv-app/EditorsSheets.apk
remove $sysroot/system/priv-app/EditorsSheets.odex
remove $sysroot/system/priv-app/EditorsSlides
remove $sysroot/system/priv-app/EditorsSlides.apk
remove $sysroot/system/priv-app/EditorsSlides.odex
remove $sysroot/system/priv-app/ExchangeServices
remove $sysroot/system/priv-app/ExchangeServices.apk
remove $sysroot/system/priv-app/ExchangeServices.odex
remove $sysroot/system/priv-app/FaceLock
remove $sysroot/system/priv-app/FaceLock.apk
remove $sysroot/system/priv-app/FaceLock.odex
remove $sysroot/system/priv-app/Finsky
remove $sysroot/system/priv-app/Finsky.apk
remove $sysroot/system/priv-app/Finsky.odex
remove $sysroot/system/priv-app/FitnessPrebuilt
remove $sysroot/system/priv-app/FitnessPrebuilt.apk
remove $sysroot/system/priv-app/FitnessPrebuilt.odex
remove $sysroot/system/priv-app/FOTAKill
remove $sysroot/system/priv-app/FOTAKill.apk
remove $sysroot/system/priv-app/FOTAKill.odex
remove $sysroot/system/priv-app/GalleryGoogle
remove $sysroot/system/priv-app/GalleryGoogle.apk
remove $sysroot/system/priv-app/GalleryGoogle.odex
remove $sysroot/system/priv-app/GCS
remove $sysroot/system/priv-app/GCS.apk
remove $sysroot/system/priv-app/GCS.odex
remove $sysroot/system/priv-app/GenieWidget
remove $sysroot/system/priv-app/GenieWidget.apk
remove $sysroot/system/priv-app/GenieWidget.odex
remove $sysroot/system/priv-app/Gmail
remove $sysroot/system/priv-app/Gmail.apk
remove $sysroot/system/priv-app/Gmail.odex
remove $sysroot/system/priv-app/Gmail2
remove $sysroot/system/priv-app/Gmail2.apk
remove $sysroot/system/priv-app/Gmail2.odex
remove $sysroot/system/priv-app/GmsCore
remove $sysroot/system/priv-app/GmsCore.apk
remove $sysroot/system/priv-app/GmsCore.odex
remove $sysroot/system/priv-app/GmsCoreSetupPrebuilt
remove $sysroot/system/priv-app/GmsCoreSetupPrebuilt.apk
remove $sysroot/system/priv-app/GmsCoreSetupPrebuilt.odex
remove $sysroot/system/priv-app/GoogleBackupTransport
remove $sysroot/system/priv-app/GoogleBackupTransport.apk
remove $sysroot/system/priv-app/GoogleBackupTransport.odex
remove $sysroot/system/priv-app/GoogleCalendar
remove $sysroot/system/priv-app/GoogleCalendar.apk
remove $sysroot/system/priv-app/GoogleCalendar.odex
remove $sysroot/system/priv-app/GoogleCalendarSyncAdapter
remove $sysroot/system/priv-app/GoogleCalendarSyncAdapter.apk
remove $sysroot/system/priv-app/GoogleCalendarSyncAdapter.odex
remove $sysroot/system/priv-app/GoogleCamera
remove $sysroot/system/priv-app/GoogleCamera.apk
remove $sysroot/system/priv-app/GoogleCamera.odex
remove $sysroot/system/priv-app/GoogleCloudPrint
remove $sysroot/system/priv-app/GoogleCloudPrint.apk
remove $sysroot/system/priv-app/GoogleCloudPrint.odex
remove $sysroot/system/priv-app/GoogleContacts
remove $sysroot/system/priv-app/GoogleContacts.apk
remove $sysroot/system/priv-app/GoogleContacts.odex
remove $sysroot/system/priv-app/GoogleContactsSyncAdapter
remove $sysroot/system/priv-app/GoogleContactsSyncAdapter.apk
remove $sysroot/system/priv-app/GoogleContactsSyncAdapter.odex
remove $sysroot/system/priv-app/GoogleDialer
remove $sysroot/system/priv-app/GoogleDialer.apk
remove $sysroot/system/priv-app/GoogleDialer.odex
remove $sysroot/system/priv-app/GoogleEars
remove $sysroot/system/priv-app/GoogleEars.apk
remove $sysroot/system/priv-app/GoogleEars.odex
remove $sysroot/system/priv-app/GoogleEarth
remove $sysroot/system/priv-app/GoogleEarth.apk
remove $sysroot/system/priv-app/GoogleEarth.odex
remove $sysroot/system/priv-app/GoogleExtServices
remove $sysroot/system/priv-app/GoogleExtServices.apk
remove $sysroot/system/priv-app/GoogleExtServices.odex
remove $sysroot/system/priv-app/GoogleExtShared
remove $sysroot/system/priv-app/GoogleExtShared.apk
remove $sysroot/system/priv-app/GoogleExtShared.odex
remove $sysroot/system/priv-app/GoogleFeedback
remove $sysroot/system/priv-app/GoogleFeedback.apk
remove $sysroot/system/priv-app/GoogleFeedback.odex
remove $sysroot/system/priv-app/GoogleHangouts
remove $sysroot/system/priv-app/GoogleHangouts.apk
remove $sysroot/system/priv-app/GoogleHangouts.odex
remove $sysroot/system/priv-app/GoogleHindiIME
remove $sysroot/system/priv-app/GoogleHindiIME.apk
remove $sysroot/system/priv-app/GoogleHindiIME.odex
remove $sysroot/system/priv-app/GoogleHome
remove $sysroot/system/priv-app/GoogleHome.apk
remove $sysroot/system/priv-app/GoogleHome.odex
remove $sysroot/system/priv-app/GoogleJapaneseInput
remove $sysroot/system/priv-app/GoogleJapaneseInput.apk
remove $sysroot/system/priv-app/GoogleJapaneseInput.odex
remove $sysroot/system/priv-app/GoogleKeep
remove $sysroot/system/priv-app/GoogleKeep.apk
remove $sysroot/system/priv-app/GoogleKeep.odex
remove $sysroot/system/priv-app/GoogleLatinIme
remove $sysroot/system/priv-app/GoogleLatinIme.apk
remove $sysroot/system/priv-app/GoogleLatinIme.odex
remove $sysroot/system/priv-app/GoogleLoginService
remove $sysroot/system/priv-app/GoogleLoginService.apk
remove $sysroot/system/priv-app/GoogleLoginService.odex
remove $sysroot/system/priv-app/GoogleMusic
remove $sysroot/system/priv-app/GoogleMusic.apk
remove $sysroot/system/priv-app/GoogleMusic.odex
remove $sysroot/system/priv-app/GoogleNow
remove $sysroot/system/priv-app/GoogleNow.apk
remove $sysroot/system/priv-app/GoogleNow.odex
remove $sysroot/system/priv-app/GoogleNowVoiceSearch
remove $sysroot/system/priv-app/GoogleNowVoiceSearch.apk
remove $sysroot/system/priv-app/GoogleNowVoiceSearch.odex
remove $sysroot/system/priv-app/GoogleOneTimeInitializer
remove $sysroot/system/priv-app/GoogleOneTimeInitializer.apk
remove $sysroot/system/priv-app/GoogleOneTimeInitializer.odex
remove $sysroot/system/priv-app/GooglePackageInstaller
remove $sysroot/system/priv-app/GooglePackageInstaller.apk
remove $sysroot/system/priv-app/GooglePackageInstaller.odex
remove $sysroot/system/priv-app/GooglePartnerSetup
remove $sysroot/system/priv-app/GooglePartnerSetup.apk
remove $sysroot/system/priv-app/GooglePartnerSetup.odex
remove $sysroot/system/priv-app/GooglePinyinIME
remove $sysroot/system/priv-app/GooglePinyinIME.apk
remove $sysroot/system/priv-app/GooglePinyinIME.odex
remove $sysroot/system/priv-app/GooglePlay
remove $sysroot/system/priv-app/GooglePlay.apk
remove $sysroot/system/priv-app/GooglePlay.odex
remove $sysroot/system/priv-app/GooglePlus
remove $sysroot/system/priv-app/GooglePlus.apk
remove $sysroot/system/priv-app/GooglePlus.odex
remove $sysroot/system/priv-app/GooglePrintRecommendationService
remove $sysroot/system/priv-app/GooglePrintRecommendationService.apk
remove $sysroot/system/priv-app/GooglePrintRecommendationService.odex
remove $sysroot/system/priv-app/GoogleQuickSearchBox
remove $sysroot/system/priv-app/GoogleQuickSearchBox.apk
remove $sysroot/system/priv-app/GoogleQuickSearchBox.odex
remove $sysroot/system/priv-app/GoogleServicesFramework
remove $sysroot/system/priv-app/GoogleServicesFramework.apk
remove $sysroot/system/priv-app/GoogleServicesFramework.odex
remove $sysroot/system/priv-app/GoogleTTS
remove $sysroot/system/priv-app/GoogleTTS.apk
remove $sysroot/system/priv-app/GoogleTTS.odex
remove $sysroot/system/priv-app/GoogleVrCore
remove $sysroot/system/priv-app/GoogleVrCore.apk
remove $sysroot/system/priv-app/GoogleVrCore.odex
remove $sysroot/system/priv-app/GoogleZhuyinIME
remove $sysroot/system/priv-app/GoogleZhuyinIME.apk
remove $sysroot/system/priv-app/GoogleZhuyinIME.odex
remove $sysroot/system/priv-app/Hangouts
remove $sysroot/system/priv-app/Hangouts.apk
remove $sysroot/system/priv-app/Hangouts.odex
remove $sysroot/system/priv-app/HangoutsDialer
remove $sysroot/system/priv-app/HangoutsDialer.apk
remove $sysroot/system/priv-app/HangoutsDialer.odex
remove $sysroot/system/priv-app/HotwordEnrollment
remove $sysroot/system/priv-app/HotwordEnrollment.apk
remove $sysroot/system/priv-app/HotwordEnrollment.odex
remove $sysroot/system/priv-app/iWnnIME
remove $sysroot/system/priv-app/iWnnIME.apk
remove $sysroot/system/priv-app/iWnnIME.odex
remove $sysroot/system/priv-app/iWnnIME_Kbd_White
remove $sysroot/system/priv-app/iWnnIME_Kbd_White.apk
remove $sysroot/system/priv-app/iWnnIME_Kbd_White.odex
remove $sysroot/system/priv-app/Keep
remove $sysroot/system/priv-app/Keep.apk
remove $sysroot/system/priv-app/Keep.odex
remove $sysroot/system/priv-app/KoreanIME
remove $sysroot/system/priv-app/KoreanIME.apk
remove $sysroot/system/priv-app/KoreanIME.odex
remove $sysroot/system/priv-app/LatinIME
remove $sysroot/system/priv-app/LatinIME.apk
remove $sysroot/system/priv-app/LatinIME.odex
remove $sysroot/system/priv-app/LatinImeDictionaryPack
remove $sysroot/system/priv-app/LatinImeDictionaryPack.apk
remove $sysroot/system/priv-app/LatinImeDictionaryPack.odex
remove $sysroot/system/priv-app/LatinImeGoogle
remove $sysroot/system/priv-app/LatinImeGoogle.apk
remove $sysroot/system/priv-app/LatinImeGoogle.odex
remove $sysroot/system/priv-app/LatinIMEGooglePrebuilt
remove $sysroot/system/priv-app/LatinIMEGooglePrebuilt.apk
remove $sysroot/system/priv-app/LatinIMEGooglePrebuilt.odex
remove $sysroot/system/priv-app/LatinImeTutorial
remove $sysroot/system/priv-app/LatinImeTutorial.apk
remove $sysroot/system/priv-app/LatinImeTutorial.odex
remove $sysroot/system/priv-app/Magazines
remove $sysroot/system/priv-app/Magazines.apk
remove $sysroot/system/priv-app/Magazines.odex
remove $sysroot/system/priv-app/Maps
remove $sysroot/system/priv-app/Maps.apk
remove $sysroot/system/priv-app/Maps.odex
remove $sysroot/system/priv-app/MarketUpdater
remove $sysroot/system/priv-app/MarketUpdater.apk
remove $sysroot/system/priv-app/MarketUpdater.odex
remove $sysroot/system/priv-app/MediaUploader
remove $sysroot/system/priv-app/MediaUploader.apk
remove $sysroot/system/priv-app/MediaUploader.odex
remove $sysroot/system/priv-app/Music2
remove $sysroot/system/priv-app/Music2.apk
remove $sysroot/system/priv-app/Music2.odex
remove $sysroot/system/priv-app/MusicFX/MusicFX.apk
remove $sysroot/system/priv-app/NetworkLocation
remove $sysroot/system/priv-app/NetworkLocation.apk
remove $sysroot/system/priv-app/NetworkLocation.odex
remove $sysroot/system/priv-app/Newsstand
remove $sysroot/system/priv-app/Newsstand.apk
remove $sysroot/system/priv-app/Newsstand.odex
remove $sysroot/system/priv-app/NexusLauncherIcons
remove $sysroot/system/priv-app/NexusLauncherIcons.apk
remove $sysroot/system/priv-app/NexusLauncherIcons.odex
remove $sysroot/system/priv-app/NexusLauncherPrebuilt
remove $sysroot/system/priv-app/NexusLauncherPrebuilt.apk
remove $sysroot/system/priv-app/NexusLauncherPrebuilt.odex
remove $sysroot/system/priv-app/OccamQuickOffice
remove $sysroot/system/priv-app/OccamQuickOffice.apk
remove $sysroot/system/priv-app/OccamQuickOffice.odex
remove $sysroot/system/priv-app/OmniStyle.apk
remove $sysroot/system/priv-app/OneTimeInitializer
remove $sysroot/system/priv-app/OneTimeInitializer.apk
remove $sysroot/system/priv-app/OneTimeInitializer.odex
remove $sysroot/system/priv-app/PartnerBookmarksProvider
remove $sysroot/system/priv-app/PartnerBookmarksProvider.apk
remove $sysroot/system/priv-app/PartnerBookmarksProvider.odex
remove $sysroot/system/priv-app/Phonesky
remove $sysroot/system/priv-app/Phonesky.apk
remove $sysroot/system/priv-app/Phonesky.odex
remove $sysroot/system/priv-app/Photos
remove $sysroot/system/priv-app/Photos.apk
remove $sysroot/system/priv-app/Photos.odex
remove $sysroot/system/priv-app/PlayAutoInstallConfig
remove $sysroot/system/priv-app/PlayAutoInstallConfig.apk
remove $sysroot/system/priv-app/PlayAutoInstallConfig.odex
remove $sysroot/system/priv-app/PlayGames
remove $sysroot/system/priv-app/PlayGames.apk
remove $sysroot/system/priv-app/PlayGames.odex
remove $sysroot/system/priv-app/PlayStore
remove $sysroot/system/priv-app/PlayStore.apk
remove $sysroot/system/priv-app/PlayStore.odex
remove $sysroot/system/priv-app/PlusOne
remove $sysroot/system/priv-app/PlusOne.apk
remove $sysroot/system/priv-app/PlusOne.odex
remove $sysroot/system/priv-app/PrebuiltBugle
remove $sysroot/system/priv-app/PrebuiltBugle.apk
remove $sysroot/system/priv-app/PrebuiltBugle.odex
remove $sysroot/system/priv-app/PrebuiltDeskClockGoogle
remove $sysroot/system/priv-app/PrebuiltDeskClockGoogle.apk
remove $sysroot/system/priv-app/PrebuiltDeskClockGoogle.odex
remove $sysroot/system/priv-app/PrebuiltEmailGoogle
remove $sysroot/system/priv-app/PrebuiltEmailGoogle.apk
remove $sysroot/system/priv-app/PrebuiltEmailGoogle.odex
remove $sysroot/system/priv-app/PrebuiltExchange3Google
remove $sysroot/system/priv-app/PrebuiltExchange3Google.apk
remove $sysroot/system/priv-app/PrebuiltExchange3Google.odex
remove $sysroot/system/priv-app/PrebuiltGmail
remove $sysroot/system/priv-app/PrebuiltGmail.apk
remove $sysroot/system/priv-app/PrebuiltGmail.odex
remove $sysroot/system/priv-app/PrebuiltGmsCore
remove $sysroot/system/priv-app/PrebuiltGmsCore.apk
remove $sysroot/system/priv-app/PrebuiltGmsCore.odex
remove $sysroot/system/priv-app/PrebuiltKeep
remove $sysroot/system/priv-app/PrebuiltKeep.apk
remove $sysroot/system/priv-app/PrebuiltKeep.odex
remove $sysroot/system/priv-app/PrebuiltNewsWeather
remove $sysroot/system/priv-app/PrebuiltNewsWeather.apk
remove $sysroot/system/priv-app/PrebuiltNewsWeather.odex
remove $sysroot/system/priv-app/PrintSpooler
remove $sysroot/system/priv-app/PrintSpooler.apk
remove $sysroot/system/priv-app/PrintSpooler.odex
remove $sysroot/system/priv-app/QuickOffice
remove $sysroot/system/priv-app/QuickOffice.apk
remove $sysroot/system/priv-app/QuickOffice.odex
remove $sysroot/system/priv-app/QuickSearchBox
remove $sysroot/system/priv-app/QuickSearchBox.apk
remove $sysroot/system/priv-app/QuickSearchBox.odex
remove $sysroot/system/priv-app/SetupWizard
remove $sysroot/system/priv-app/SetupWizard.apk
remove $sysroot/system/priv-app/SetupWizard.odex
remove $sysroot/system/priv-app/StorageManagerGoogle
remove $sysroot/system/priv-app/StorageManagerGoogle.apk
remove $sysroot/system/priv-app/StorageManagerGoogle.odex
remove $sysroot/system/priv-app/Street
remove $sysroot/system/priv-app/Street.apk
remove $sysroot/system/priv-app/Street.odex
remove $sysroot/system/priv-app/Tag/Tag.apk
remove $sysroot/system/priv-app/TagGoogle
remove $sysroot/system/priv-app/TagGoogle.apk
remove $sysroot/system/priv-app/TagGoogle.odex
remove $sysroot/system/priv-app/Talk
remove $sysroot/system/priv-app/Talk.apk
remove $sysroot/system/priv-app/Talk.odex
remove $sysroot/system/priv-app/talkback
remove $sysroot/system/priv-app/talkback.apk
remove $sysroot/system/priv-app/talkback.odex
remove $sysroot/system/priv-app/TranslatePrebuilt
remove $sysroot/system/priv-app/TranslatePrebuilt.apk
remove $sysroot/system/priv-app/TranslatePrebuilt.odex
remove $sysroot/system/priv-app/Tycho
remove $sysroot/system/priv-app/Tycho.apk
remove $sysroot/system/priv-app/Tycho.odex
remove $sysroot/system/priv-app/Velvet
remove $sysroot/system/priv-app/Velvet.apk
remove $sysroot/system/priv-app/Velvet.odex
remove $sysroot/system/priv-app/Vending
remove $sysroot/system/priv-app/Vending.apk
remove $sysroot/system/priv-app/Vending.odex
remove $sysroot/system/priv-app/Videos
remove $sysroot/system/priv-app/Videos.apk
remove $sysroot/system/priv-app/Videos.odex
remove $sysroot/system/priv-app/VoiceSearch
remove $sysroot/system/priv-app/VoiceSearch.apk
remove $sysroot/system/priv-app/VoiceSearch.odex
remove $sysroot/system/priv-app/VoiceSearchStub
remove $sysroot/system/priv-app/VoiceSearchStub.apk
remove $sysroot/system/priv-app/VoiceSearchStub.odex
remove $sysroot/system/priv-app/Wallet
remove $sysroot/system/priv-app/Wallet.apk
remove $sysroot/system/priv-app/Wallet.odex
remove $sysroot/system/priv-app/WallpaperPickerGooglePrebuilt
remove $sysroot/system/priv-app/WallpaperPickerGooglePrebuilt.apk
remove $sysroot/system/priv-app/WallpaperPickerGooglePrebuilt.odex
remove $sysroot/system/priv-app/YouTube
remove $sysroot/system/priv-app/YouTube.apk
remove $sysroot/system/priv-app/YouTube.odex
remove $sysroot/system/tts
remove $sysroot/system/usr/srec
remove $sysroot/system/vendor/lib/libfrsdk.so
remove $sysroot/system/vendor/lib64/libfrsdk.so
remove $sysroot/system/vendor/pittpatt
